AWSTemplateFormatVersion: 2010-09-09
Description: >-
  EB-SQS #magic___^_^___line
Transform:
- AWS::Serverless-2016-10-31

Resources:

  PutEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putEvents.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP post method to post all items.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /generate
            Method: POST

    # event bus
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: EB_SQS_EventBus


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  PutEventFunction:
    Description: "PutEventFunction ARN"
    Value: !GetAtt PutEventFunction.Arn

  EventBus:
    Description: "EventBus ARN"
    Value: !GetAtt EventBus.Arn
